defmodule Astraplex.Repo.Migrations.CreateConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :conversation_id, :uuid
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :member_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:conversations, [:member_hash],
             name: "conversations_unique_member_set_index"
           )

    create table(:conversation_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_memberships_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "conversation_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:conversation_memberships, [:conversation_id, :user_id],
             name: "conversation_memberships_unique_conversation_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(:conversation_memberships, [:conversation_id, :user_id],
                     name: "conversation_memberships_unique_conversation_membership_index"
                   )

    drop constraint(:conversation_memberships, "conversation_memberships_conversation_id_fkey")

    drop constraint(:conversation_memberships, "conversation_memberships_user_id_fkey")

    drop table(:conversation_memberships)

    drop_if_exists unique_index(:conversations, [:member_hash],
                     name: "conversations_unique_member_set_index"
                   )

    alter table(:conversations) do
      remove :updated_at
      remove :inserted_at
      remove :member_hash
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    alter table(:messages) do
      remove :conversation_id
    end
  end
end
